INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (1, 'Anti-Mage', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (2, 'Axe', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (3, 'Bane', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (4, 'Bloodseeker', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (5, 'Crystal Maiden', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (6, 'Drow Ranger', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (7, 'Earthshaker', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (8, 'Juggernaut', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (9, 'Mirana', 1, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (10, 'Morphling', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (11, 'Shadow Fiend', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (12, 'Phantom Lancer', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (13, 'Puck', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (14, 'Pudge', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (15, 'Razor', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (16, 'Sand King', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (17, 'Storm Spirit', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (18, 'Sven', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (19, 'Tiny', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (20, 'Vengeful Spirit', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (21, 'Windranger', 1, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (22, 'Zeus', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (23, 'Kunkka', 1, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (25, 'Lina', 1, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (26, 'Lion', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (27, 'Shadow Shaman', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (28, 'Slardar', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (29, 'Tidehunter', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (30, 'Witch Doctor', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (31, 'Lich', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (32, 'Riki', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (33, 'Enigma', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (34, 'Tinker', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (35, 'Sniper', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (36, 'Necrophos', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (37, 'Warlock', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (38, 'Beastmaster', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (39, 'Queen of Pain', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (40, 'Venomancer', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (41, 'Faceless Void', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (42, 'Wraith King', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (43, 'Death Prophet', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (44, 'Phantom Assassin', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (45, 'Pugna', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (46, 'Templar Assassin', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (47, 'Viper', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (48, 'Luna', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (49, 'Dragon Knight', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (50, 'Dazzle', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (51, 'Clockwerk', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (52, 'Leshrac', 0, 1, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (53, 'Nature''s Prophet', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (54, 'Lifestealer', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (55, 'Dark Seer', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (56, 'Clinkz', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (57, 'Omniknight', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (58, 'Enchantress', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (59, 'Huskar', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (60, 'Night Stalker', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (61, 'Broodmother', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (62, 'Bounty Hunter', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (63, 'Weaver', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (64, 'Jakiro', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (65, 'Batrider', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (66, 'Chen', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (67, 'Spectre', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (68, 'Ancient Apparition', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (69, 'Doom', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (70, 'Ursa', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (71, 'Spirit Breaker', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (72, 'Gyrocopter', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (73, 'Alchemist', 1, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (74, 'Invoker', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (75, 'Silencer', 1, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (76, 'Outworld Destroyer', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (77, 'Lycan', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (78, 'Brewmaster', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (79, 'Shadow Demon', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (80, 'Lone Druid', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (81, 'Chaos Knight', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (82, 'Meepo', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (83, 'Treant Protector', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (84, 'Ogre Magi', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (85, 'Undying', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (86, 'Rubick', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (87, 'Disruptor', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (88, 'Nyx Assassin', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (89, 'Naga Siren', 1, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (90, 'Keeper of the Light', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (91, 'Io', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (92, 'Visage', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (93, 'Slark', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (94, 'Medusa', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (95, 'Troll Warlord', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (96, 'Centaur Warrunner', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (97, 'Magnus', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (98, 'Timbersaw', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (99, 'Bristleback', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (100, 'Tusk', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (101, 'Skywrath Mage', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (102, 'Abaddon', 1, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (103, 'Elder Titan', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (104, 'Legion Commander', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (105, 'Techies', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (106, 'Ember Spirit', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (107, 'Earth Spirit', 1, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (108, 'Underlord', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (109, 'Terrorblade', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (110, 'Phoenix', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (111, 'Oracle', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (112, 'Winter Wyvern', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (113, 'Arc Warden', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (114, 'Monkey King', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (119, 'Dark Willow', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (120, 'Pangolier', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (121, 'Grimstroke', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (123, 'Hoodwink', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (126, 'Void Spirit', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (128, 'Snapfire', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (129, 'Mars', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (131, 'Ringmaster', 0, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (135, 'Dawnbreaker', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (136, 'Marci', 1, 0, 0, 1);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (137, 'Primal Beast', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (138, 'Muerta', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (145, 'Kez', 1, 0, 0, 0);
INSERT OR IGNORE INTO heroes (hero_id, name, is_carry, is_mid, is_offlane, is_support) VALUES (155, 'Largo', 0, 0, 0, 1);
